### ISSUE TITLE
Some questions about implementation.

### ISSUE THREAD

**Issue by swordfate** [SJTU-IPADS/gnnlab#3]
I am a little confused:( about the functions of some objects when I go through the code of `GPUEngine::Init()` (in line 64 of file `samgraph/common/cuda/cuda_engine.cc`), and I failed to find code comments about them. Can you explain the function of the following objects? 
```python
1. _shuffler = new GPUShuffler(_dataset->train_set, _num_epoch, _batch_size, false); 
2. _hashtable = new OrderedHashTable(PredictNumNodes(_batch_size, _fanout, _fanout.size()), _sampler_ctx);
3. _queues.push_back(new TaskQueue(RunConfig::max_sampling_jobs)); # I see `QueueType { kGPUSample = 0, kDataCopy, kNumQueues };` but what do they represent?
4. _graph_pool = new GraphPool(RunConfig::max_copying_jobs);
```
By the way, can you provide a few instructions on how to understand the enormous code? I would be very grateful if you could give any hints :). I am looking forward to your reply!

**Comment by molamooo** [comment]
1. `shuffler` shuffles the entire train set at the end of each epoch. This automatically done when shuffler detects that num_step batches are retrived.
2. hashtable is used to dedup sampled node at each layer
3. `kGPUSample` is preserved and never used. `kDataCopy` is the queue to transfer sampled graph between sampler & extractor.
4. graph pool is for extractor to place extracted subgraph. Each time trainer calls `get_next_batch`, one batch is take out from the pool. It's actually a queue between extractor and trainer, similar to the queue between sampler and extractor.

Sorry for the absence of comments... In most cases, you may do a global search on where these objects are used.

I see that you are reading codes about `GPUEngine`. When running gnnlab from `example/samgraph/train_*`, at most  one sampler and one trainer can be used, and they are in one process. To support multiple sampler and multiple trainer, we later implemented `DistEngine`, where each sampler and trainer runs under different processes. Related examples are at `example/samgraph/multi_gpu/train_*`. The mode is set by the `arch` parameter in config(it's hidden so you may not explicitly  set this parameter).`arch3` refers to the single process mode, and `arch5` refers to the multi process mode. Other arch is designed for other baseline modes. You may see switch statements on `RunConfig::run_arch` during luanch, which initializes different engines:
1. python calls to `sam.init()`
2. library function `samgraph_init` in `samgraph/common/operation.cc` is called using ffi.
3. `Engine::Create()` creates engine singleton.

All major experiments in `exp` is actually using `DistEngine`, not `GPUEngine`. But you may continue read code in `GPUEngine`, which should gives you a quick overview on the codebase, since code in `DistEngine` is rather moew complicated.

**Comment by swordfate** [comment]
> 1. `shuffler` shuffles the entire train set at the end of each epoch. This automatically done when shuffler detects that num_step batches are retrived.
> 2. hashtable is used to dedup sampled node at each layer
> 3. `kGPUSample` is preserved and never used. `kDataCopy` is the queue to transfer sampled graph between sampler & extractor.
> 4. graph pool is for extractor to place extracted subgraph. Each time trainer calls `get_next_batch`, one batch is take out from the pool. It's actually a queue between extractor and trainer, similar to the queue between sampler and extractor.
> 
> Sorry for the absence of comments... In most cases, you may do a global search on where these objects are used.
> 
> I see that you are reading codes about `GPUEngine`. When running gnnlab from `example/samgraph/train_*`, at most one sampler and one trainer can be used, and they are in one process. To support multiple sampler and multiple trainer, we later implemented `DistEngine`, where each sampler and trainer runs under different processes. Related examples are at `example/samgraph/multi_gpu/train_*`. The mode is set by the `arch` parameter in config(it's hidden so you may not explicitly set this parameter).`arch3` refers to the single process mode, and `arch5` refers to the multi process mode. Other arch is designed for other baseline modes. You may see switch statements on `RunConfig::run_arch` during luanch, which initializes different engines:
> 
> 1. python calls to `sam.init()`
> 2. library function `samgraph_init` in `samgraph/common/operation.cc` is called using ffi.
> 3. `Engine::Create()` creates engine singleton.
> 
> All major experiments in `exp` is actually using `DistEngine`, not `GPUEngine`. But you may continue read code in `GPUEngine`, which should gives you a quick overview on the codebase, since code in `DistEngine` is rather moew complicated.

I am sincerely grateful for your detailed and patient reply. With the help of your explanation, I have more understanding of the code, and thank you again. I will close this problem first.

**Comment by swordfate** [comment]
When I read the code in `example/samgraph/sgnn/train_*`, I noticed that **sgnn was running on multiple GPUs using DDP**. First, `DistEngine` is initialized by calling `samgraph_data_init()` and produces **an `_engine` singleton** as you mentioned above. Then, the main function creates sub-processes for each GPU through `mp.Process()` to execute their own `sample_init()` and `train_init()`. 

My question is: **Since different sub-processes will access the only `_engine` singleton, will they assign multiple times to a same variable in _engine singleton**? 
For example, each sub-process on each GPU will execute `_initialize=True` at the end of their own function `sample_init()` but only one `_initialize` exists in C++ singleton `_engine`.
Another example, each sub-process on each GPU will  assign the only one C++ `_sample_ctx` attribute with their own `ctx` by executing `sample_init()`.

I am very grateful if you could give some explanations. Looking forward to your reply~ :)

**Comment by molamooo** [comment]
Once forked, the parent and child process does not share memory, unless you create shared memory explicitly(i.e. mmap with SHARED flag). The engine singleton is created before creating sub-processes. After `mp.Process()`, all children's memory are identical but **independent**. So modifications in one process does not affect another process. This is the behavior of operating system, not GNNLab.

**Comment by swordfate** [comment]
> 



> Once forked, the parent and child process does not share memory, unless you create shared memory explicitly(i.e. mmap with SHARED flag). The engine singleton is created before creating sub-processes. After `mp.Process()`, all children's memory are identical but **independent**. So modifications in one process does not affect another process. This is the behavior of operating system, not GNNLab.

Do you mean the singleton `_engine` will be copied in each child process' memory space?

**Comment by molamooo** [comment]
Yes. Everything is identical in all children's memory right after the creation of these process.

**Comment by swordfate** [comment]
> Yes. Everything is identical in all children's memory right after the creation of these process.

I got it! Very grateful for your clear and detailed reply 👍, thanks! I will close this issue and turn on again when necessary. :)
