### ISSUE TITLE
Run gnnlab with smaller batch size

### ISSUE THREAD

**Issue by lwwlwwl** [SJTU-IPADS/gnnlab#7]
Hi, I was trying to run gnnlab with a batch size of 100 while was given the error as `F /app/source/fgnn/samgraph/common/dist/dist_engine.cc:273] Num step exceeds max length of memory queue. Please increase 'mq_size' and re-compile!`. So, I went to directory `fgnn/samgraph/common/memory_queue.h` to set `constexpr size_t mq_size = 500;` instead of 170. However, when I tried to run again with 100 as batch size, the change did not seem to take effect. I am wondering what modification I should do to be able to run both products and papers with batch size of 100 in a single GPU setting. Thanks in advance!

**Comment by lixiaobai09** [comment]
One of the main ideas in GNNLab is space sharing on multiple GPUs, so you can run GNNLab on a multi-GPU platform to get better performance.

And this is the GNNLab progress on a single GPU:  GNNLab first **stores all samples(sampling results of mini-batches) of an epoch in the host memory queue**; after that, the standby Trainer is launched to conduct model training to consume the samples. The GNNLab with no pipeline mode is the same.

So the user should **set the `mq_size` larger than `trainset_size / batch_size`** on a single GPU.

On the multi-GPU platform with a pipeline running mode, because the samples in the memory queue always can be consumed by the Trainer asynchronously, so user can even annotate `dist_engine.cc:273` to solve this problem.

**Comment by lwwlwwl** [comment]
Thanks for your reply. 

I am wondering which file of mq_size I should set. I tried to set mq_size in the `memory_quque.h` to large enough or just have ` if (_shuffler->NumStep() > 2000) {` instead of ` if (_shuffler->NumStep() > mq_size) {` in `dist_engine.cc:272`. However, the value of mq_size did not seem to be changed. 

(batch_size=1200 is the lowest batch size can be used for products with the default mq_size value. I tried to lower mq_size to see if the change has been applied by setting mq_size to 100, but it can still be ran. So I think somehow the change of mq_size value was not taken)

**Comment by lixiaobai09** [comment]
You can change the `mq_size` in the file `samgraph/common/memory_queue.h` [here](https://github.com/SJTU-IPADS/gnnlab/blob/main/samgraph/common/memory_queue.h#L46). After that, you should **rebuild** the GNNLab source code and install it again to use the new `mq_size` value.

**Comment by lwwlwwl** [comment]
Ahh I need to rebuild the whole thing. It works now. Thank you!

**Comment by lwwlwwl** [comment]
Hi, I am trying to run a bigger dataset (trainset_size = 656000) with batch_size=100. Following suggestions above, I set mq_size to be 6700 and rebuild the docker. However, with this being changed, when running the training command, I got the following error 
```
[2023-02-01 01:55:47.966963: F /app/source/fgnn/samgraph/common/memory_queue.cc:38] Check failed: (_meta_data) != (((void *) -1))
Aborted (core dumped)
```
Is there any upper limit for the value of mq_size?

**Comment by lixiaobai09** [comment]
Too many batches may cause too much memory footprint. Your problem may be from memory exceeding. You can change each batch's _sampling result storage size_ in the memory queue to reduce memory occupancy.
To reduce each batch's _sampling result storage size_ in the memory queue, you can modify the value `mq_nbytes` in `L32` of file `samgraph/common/task_queue.cc`. Then re-compile the codes.
